name: CI

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Syntax check
        run: python -m py_compile bot.py

      - name: Import smoke test
        run: |
          python - <<'PY'
          import bot
          print(\"✅ bot.py import OK (no runtime executed)\")
          PY

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ruff (fast linter)
        run: pip install ruff

      - name: Ruff check
        run: ruff check .
